### ISSUE TITLE
ASB list

### ISSUE THREAD

**Issue by zhangpicb** [aanderson54/BrainTF_ASB#1]
Dear @aanderson54 

Thanks for the great paper https://genome.cshlp.org/content/early/2024/08/16/gr.278601.123#aff-3

I want to use the ASB snp list information,but the supplementary data are unavilable.Synapse link is also unavilable.

Thanks in advanced!

**Comment by aanderson54** [comment]
Hi thanks for reaching out about the data. All supplemental files will become available once the paper is officially published. I've gone ahead and added SuppTable4 to the GitHub page as well. This file includes the list of all ASB variants. 

The synapse link should be active and under the accession code syn51942384. However, PsychENCODE is in the process of migrating all data from synapse to NDA, so data access requests make take longer to complete.

Best,
Ashlyn

**Comment by zhangpicb** [comment]
Dear @aanderson54 

Thanks for your quick reply!

SuppTable4 don't have the information about if the SNP in the TF motif.
Maybe other supptable have this information.

Thanks in advanced!

**Comment by aanderson54** [comment]
I've added SuppTable5 as well. This has all of the motifbreakR results. 

Ashlyn
